### ISSUE TITLE
На lostfilmfeed.petproject.by невозможно пройти капчу

### ISSUE THREAD

**Issue by avt00** [lAnubisl/LostFilmTorrentsFeed#1]
Всё в заголовке. Пробовал через нескольких браузеров, при регистрации всегда ответ что капча введена с ошибкой.

**Comment by lAnubisl** [comment]
Починил ошибку регистрации. Если проблема при вводе кэпчи - оно будет писать 
`"Судя по всему, число введено не верно."`

**Comment by wishmanster** [comment]
Капча по прежднему не проходиться. Пишет "Произошла ошибка при регистрации. Обратитесь к администратору."

**Comment by lAnubisl** [comment]
Воспроизвёл. Постараюсь сегодня почнинить

**Comment by wishmanster** [comment]
> Воспроизвёл. Постараюсь сегодня почнинить

Есть каие-то новости?

**Comment by lAnubisl** [comment]
Постоянно что-то менялост на сайте в плане регистрации. Сайчас там стоит капча от гугла, поэтому я пересмотрел процесс регистрации. Вместо автоматического создания аккаунта теперь при регистрации нужно указать ключи уже существующего аккаунта.
