### ISSUE TITLE
Использование одного аккаунта на разных устройствах

### ISSUE THREAD

**Issue by anti-spy** [lAnubisl/LostFilmTorrentsFeed#117]
Здравствуйте. Все работает вроде четко, захотел зайти в настройки фида не с компа а с планшета. Ввел тот же самый trackerid но вместо своего фида, у меня открылся полностью пустой. Как зайти в свой уже заполненный фид?

**Comment by lAnubisl** [comment]
Здравствуйте. Я сейчас в отпуске и не могу воспроизвести проблему. Вернусь из отпуска 1 сентября и попробую. Какой у Вас планшет?

**Comment by anti-spy** [comment]
У меня планшет на хармони ос, он же полный клон андроида. Huawei MatePad 11.  Но не думаю, что дело вообще зависит от моего устройства.  Открывал через Firefox на планшете.

**Comment by lAnubisl** [comment]
Попробуйте выполнить вход
![image](https://github.com/lAnubisl/LostFilmTorrentsFeed/assets/1249671/aac582bf-8f11-4992-96ee-0eb3d4e58498)
и ввести ID вот этот, который можно найти на странице пользователя на компе, на котором вы залогинены
![image](https://github.com/lAnubisl/LostFilmTorrentsFeed/assets/1249671/6906ad3c-db40-4223-b2a0-04bc646ea955)
