### ISSUE TITLE
too many connections from single user to file

### ISSUE THREAD

**Issue by lAnubisl** [lAnubisl/LostFilmTorrentsFeed#14]
after fixing this bug #8 there is a new problem:
![image](https://user-images.githubusercontent.com/1249671/123816315-e2e74700-d8ff-11eb-8e33-ccb38ccf0d22.png)

This happends because torrent file fix procedure uses single user identifier. I was hoping I will not need to ask user to paste new identifier but looks like I have to.

**Comment by anarchyst47** [comment]
Приветствую! Да, наблюдаю такую ошибку у 1080p версий, вероятно их больше всего качают! И понимаю что нужно подставлять свой персональный идентификатор, но тогда пропадает смысл в этом решении потому что отсутствует необходимая автоматизация. Лично мне нужно скачать с ленты и раздавать без дополнительных телодвижений)
В догонку вопрос - почему подгружаются некие универсальные ссылки (с вашим идентификатором), а не для каждого пользователя вашего ресурса свои?

**Comment by lAnubisl** [comment]
> Но тогда пропадает смысл в этом решении потому что отсутствует необходимая автоматизация. Лично мне нужно скачать с ленты и раздавать без дополнительных телодвижений)

Судя по всему у каждого пользователя есть ещё 1 свой уникальный id на трекере. В следующей версии (будет через пару дней) будет инструкция где его взять и я надеюсь, что проблема решится.

> В догонку вопрос - почему подгружаются некие универсальные ссылки (с вашим идентификатором), а не для каждого пользователя вашего ресурса свои?

Не было раньше этого id для каждого пользователя. Скоро будет.

**Comment by lAnubisl** [comment]
Fixed with #16

**Comment by lAnubisl** [comment]
@anarchyst47 на странице "Моя подписка" теперь можно ввести TrackerId. Проверьте пожалуйста что у вас всё работает.

**Comment by anarchyst47** [comment]
Работает, сервис - топчик!
