### ISSUE TITLE
Запрет повторного скачивания!

### ISSUE THREAD

**Issue by lAnubisl** [lAnubisl/LostFilmTorrentsFeed#27]
### Discussed in https://github.com/lAnubisl/LostFilmTorrentsFeed/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **anarchyst47** November 17, 2021</sup>
Приветствую! Заметил что иногда в RSS-ленту лоста залетают старые серии, возможно они что-то в них меняют (перевод там и пр.), хотя размеры обычно совпадают. И я бы хотел иметь возможность этого избежать, чтобы и повторно ее не качать и даже если она уже на раздаче что-то типо ошибки получается. То есть чтобы сервис, единожды выдав мне конкретную серию больше мне ее не предлагал, надеюсь смог объяснить) 

![osn1](https://user-images.githubusercontent.com/86853763/142186626-a328747c-1bf2-40de-b395-6c651607a351.jpg)
![osn2](https://user-images.githubusercontent.com/86853763/142186647-bf5d61d2-3883-4971-b465-1278cf54dbdf.jpg)
</div>

**Comment by lAnubisl** [comment]
Проблема ясна. Сделаем

**Comment by lAnubisl** [comment]
Проблема вроде как решена. Проверьте плиз.

**Comment by wws13** [comment]
а это не изза этого теперь нету ссылок на Westworld второго сезона?
Lost сейчас выпускается одновременно второй и четвертый, но ссылки в rss есть только на четвертый

**Comment by lAnubisl** [comment]
Да. К сожалению из-за этого. Я не предполагал что жпизоды будут выходить не по порядку. Поправим
