### ISSUE TITLE
Скачивание сезона

### ISSUE THREAD

**Issue by brightsider** [lAnubisl/LostFilmTorrentsFeed#28]
Можно как-то отключить скачивание сезона? Заканчиваю сезон смотреть и оно скачивает его полностью, когда мне это не нужно. Был бы благодарен за возможность это отключить

**Comment by lAnubisl** [comment]
Вроде получилось отфильтовать сезоны. С новой публикацией сайта изменения вступят в силу

**Comment by brightsider** [comment]
Спасибо)
