### ISSUE TITLE
Перестало работать

### ISSUE THREAD

**Issue by brightsider** [lAnubisl/LostFilmTorrentsFeed#29]
Последнее обновление 3 марта

**Comment by lAnubisl** [comment]
Да. Они опять всё сломали. http://[insearch.site/rssdd.xml](http://insearch.site/rssdd.xml) больше не обновляются тайтлы эпизодов. Сейчас напишу в их саппорт и подумаю что можно ещё сделать

**Comment by lAnubisl** [comment]
Написал в саппорт

**Comment by brightsider** [comment]
Починили, спасибо
