### ISSUE TITLE
Wrong thumbnail for serial

### ISSUE THREAD

**Issue by AMerkuri** [lAnubisl/LostFilmTorrentsFeed#3]
![image](https://user-images.githubusercontent.com/969989/76682352-254e1d00-6604-11ea-91ba-f21ef6d5da6d.png)

**Comment by lAnubisl** [comment]
I confirm the problem. Thumbnails are generating automatically. Unfortunately LostFilm.tv does not provide correct thumbnails sometimes. I will think how to workaround this.
