### ISSUE TITLE
Новые сериалы

### ISSUE THREAD

**Issue by brightsider** [lAnubisl/LostFilmTorrentsFeed#30]
Новые сериалы не подтягиваются в ленте. Например, Upload, Diabolical

**Comment by brightsider** [comment]
Upload появился, но без обложки, как и Picar, но вот Diabolical так и нет (
<img width="854" alt="image" src="https://user-images.githubusercontent.com/4996231/160329816-066d6666-d05d-47af-8cfc-a05e0b11a7e3.png">

**Comment by lAnubisl** [comment]
Проблема в том, что сайт lostfilm.tv находится за cloudflare который даёт защиту от скриптов. Я в очередной раз вроде обошел защиту, с новой публикацией сайта все картинки появятся.

**Comment by brightsider** [comment]
Спасибо
