### ISSUE TITLE
Зеркало

### ISSUE THREAD

**Issue by brightsider** [lAnubisl/LostFilmTorrentsFeed#32]
Добрый день.
С Украины перестал грузится сайт, нет ли какого-то зеркала на другом домене?
И как можно запустить на маке, вижу только папку для винды

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4996231/159212963-5de67406-aef2-46fe-9dc5-c1baa79b6f2e.png">

**Comment by brightsider** [comment]
Попробовал VPN из США, Беларуси - не работает тоже. Видимо проблема в чем-то другом

**Comment by lAnubisl** [comment]
я писал вчера в дискуссиих что пару дней не будет работать. Хостинг был у меня в шкафу на RaspberryPI. Я покинул страну и пока не перенёс данные на облачный хостинг. Сейчас присматриваюсь к ценам. Возможно придётся вкрутить рекламу чтобы оплачивать его =)

**Comment by brightsider** [comment]
Извиняюсь, не видел.
Спасибо за информацию, буду ждать)

**Comment by lAnubisl** [comment]
Извиняюсь за долгое отсутствие. Я перенёс хостинг на DigitalOcean. Должно всё снова работать

**Comment by brightsider** [comment]
Спасибо, работает
