### ISSUE TITLE
Restore user key if lost

### ISSUE THREAD

**Issue by ZeDima** [lAnubisl/LostFilmTorrentsFeed#4]
Невозможно восстановить уникальный ключ пользователя если нигде его не записывали. После обновления НАС-а я не могу восстановить фид к сожалению.

**Comment by lAnubisl** [comment]
Сервис написан таким образом, чтобы ничего про вас не знать. Совсем. Предполагается, что сразу после регистрации вы скопируете свой персонализированный линк, в котором зашит ключ. Если у вас нет ссылки и вы не ходите на персонализированную ленту - со временем система забудет вас совсем. 
В вашем случае проще зарегистрироваться заново.

**Comment by ZeDima** [comment]
Да, в этом есть смысл... Вот только регистрация почему-то не работает на данный момент. Спасибо тем не менее.

**Comment by lAnubisl** [comment]
Пожалуйста проверьте регистрацию ещё раз. Я её недавно чинил. Регистрация создаёт учётную запись на LostFilm - и эта часть была сломана из-за изменений на сайте LostFilm. Сейчас должна работать.

**Comment by ZeDima** [comment]
Благодарю. Работает отлично. Спасибо вам за труды. Раньше был litr.cc но с
недавних пор он перестал работать. Ваш сервис единственный способ без
"горождения граблей" настроить автоматическую скачку новых серий на QNAP-е.

*Dumitru Zeru*

**Comment by Djaler** [comment]
Здравствуйте. Регистрация сейчас не работает, а я переезжаю на другой компьютер, не получается перенести авторизацию

**Comment by Djaler** [comment]
Upd: обнаружил, что ключ можно найти в cookie UserId

**Comment by lAnubisl** [comment]
Положил ключ на странице "Моя подписка"
![image](https://user-images.githubusercontent.com/1249671/116873866-0f912200-ac21-11eb-8f0b-05767a3a6a68.png)
