### ISSUE TITLE
XML парсер спотыкается о неэкранированные &

### ISSUE THREAD

**Issue by shemanaev** [lAnubisl/LostFilmTorrentsFeed#5]
Как всегда никто не следует стандартам и на "Love, Death & Robots" всё сломалось.
Как быстрофикс использовал [такой вариант](https://stackoverflow.com/a/52951144) замены.

**Comment by lAnubisl** [comment]
Самое интересное, что я вчера наткнулся на тот же баг в базовом фиде и поэтому мой сервис не мог прочитать ничего начиная с Love, Death & Robots. А оказалось у самого рыльце в пушку. Я выпущу фикс сегодня.

**Comment by lAnubisl** [comment]
@shemanaev Я проверил и вроде всё у экраноровано. Не могли бы вы проверить ещё раз у себя?

**Comment by shemanaev** [comment]
>  баг в базовом фиде

Я именно о нём, стоило уточнить.
У меня проект локально в докере крутится просто.
